name: Deploy Workflow

on:
  push:
    branches: 
    - main

permissions:
  contents: read
  packages: write

jobs:
  Quality_SonarQube:
    uses: ./.github/workflows/01-sonarqube.yaml
    secrets: inherit

  deploy:
    needs: Quality_SonarQube
    uses: ./.github/workflows/02-DeployAzure.yaml
    secrets: inherit